apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ohif-viewer
  name: ohif-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ohif-viewer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ohif-viewer
    spec:
      containers:
        - image: webapp:latest
          name: webapp
          ports:
            - containerPort: 443
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
