apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc
  name: orthanc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orthanc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: orthanc
    spec:
      containers:
        - image: jodogne/orthanc-plugins:1.9.7
          name: orthanc
          resources: {}
          volumeMounts:
            - mountPath: /etc/orthanc/orthanc.json
              name: orthanc-claim0
              readOnly: true
            - mountPath: /var/lib/orthanc/db/
              name: orthanc-claim1
      hostname: orthanc
      restartPolicy: Always
      volumes:
        - name: orthanc-claim0
          persistentVolumeClaim:
            claimName: orthanc-claim0
            readOnly: true
        - name: orthanc-claim1
          persistentVolumeClaim:
            claimName: orthanc-claim1
status: {}
